<?php
namespace App\Models\Transaksi;
use Illuminate\Database\Eloquent\Model;
class PinjamanDaftarModels extends Model
{
    protected $table = 'ljk_aplikasi_pendaftaran';
    public $timestamps = true;
    public $autoincrement = false;
    public $incrementing  = false;
    protected $primaryKey = "id";
    protected $fillable = [
        'id',
        'id_nasabah',
        'no_dokumen',
        'kode_nasabah',
        'nik_nasabah',
        'nama_lengkap',
        'pinjaman_tujuan',
        'pinjaman_rencana',
        'pinjaman_jangkawaktu',
        'pinjaman_jangkawaktu_jenis',
        'pinjaman_jenis',
        'pinjaman_catatan',
        'usaha_nama',
        'usaha_sumberpenghasilan',
        'usaha_penghasilan',
        'usaha_pasangan_nama',
        'usaha_pasangan_alamat',
        'usaha_pasangan_kelurahan',
        'usaha_pasangan_kecamatan',
        'usaha_pasangan_kota',
        'usaha_pasangan_provinsi',
        'usaha_pasangan_kodepos',
        'usaha_pasangan_telp1',
        'usaha_pasangan_telp2',
        'usaha_pasangan_penghasilan',
        'penghasilan_pemohon',
        'penghasilan_pasangan',
        'penghasilan_usaha_lain',
        'penghasilan_tambahan',
        'penghasilan_total',
        'pengeluaran_rumahtangga',
        'pengeluaran_pendidikan',
        'pengeluaran_angsuran',
        'pengeluaran_transportasi',
        'pengeluaran_lain',
        'pengeluaran_total',
        'jaminan_jenis',
        'jaminan_namapemilik',
        'jaminan_buktipemilik',
        'jaminan_hubungan',
        'jaminan_uraian',
        'jaminan_lokasi',
        'jaminan_njop',
        'jaminan_nilai',
        'jaminan_pengikat',
        'jaminan_tambahan',
        'jaminan_tambahanpemilik',
        'jaminan_tambahanbukti',
        'jaminan_tambahanlokasi',
        'jaminan_tambahannjop',
        'jaminan_tambahannilai',
        'pj_nama',
        'pj_status',
        'pj_alamat',
        'pj_kelurahan',
        'pj_kecamatan',
        'pj_kota',
        'pj_provinsi',
        'pj_pekerjaan',
        'pj_tempat_lahir',
        'pj_tanggal_lahir',
        'pj_nik',
        'status',
        'id_kantor',
        'user_at',
        'created_at',
        'updated_at',
        'jaminan_tanpa_agunan',
        'jaminan_id',
        'status_anggota',
        'ketua',
        'pj_jenis_kelamin'
    ];
}
