<?php
namespace App\Models\Transaksi;
use Illuminate\Database\Eloquent\Model;
class PinjamanSurvey5C1PModels extends Model
{
    protected $table = 'tbl_survei_calon_nasabah_5c1p';
    public $timestamps = true;
    public $autoincrement = false;
    public $incrementing  = false;
    protected $primaryKey = "id";
    protected $fillable = [
        'id',
        'id_survei',
        'nama_alias',
        'jumlah_tetangga',
        'bi_checking',
        'gc_tags',
        'gc_tag_nama',
        'gc_tag_negatif',
        'pendapat_tetangga',
        'suka_berjudi',
        'suka_berhutang',
        'suka_mabuk',
        'penghasilan_perbulan',
        'penghasilan_pasangan',
        'jumlah_tanggungan',
        'bukti_slip_gaji',
        'keberadaan_nasabah',
        'keterangan_waktu_tertentu',
        'angsuran_nasabah_max',
        'status_jaminan',
        'status_stnk',
        'tahun_stnk_mati',
        'status_bpkp',
        'jarak_rumah_km',
        'jarak_rumah_menit',
        'kondisi_jalan',
        'memiliki_tv',
        'memiliki_kulkas',
        'kendaraan_lain',
        'nama_kendaraan_lain',
        'asset_lain',
        'tujuan_pengajuan_dana',
        'tujuan_pengajuan_dana_lain',
        'validasi_surveyor',
        'user_at',
        'created_at',
        'updated_at',
        'get_contact',
        'tag_nama_nasabah',
        'tag_negatif',
        'file_get_contact1',
        'file_get_contact2',
        'pernah_meminjam',
        'pernah_meminjam_status',
        'nama_tetangga',
        'no_telp_tetangga',
        'kondisi_rumah_tangga',
        'konotasi_negatif',
        'hasik_bi_checking',
        'pendidikan_anak',
        'pendidikan_biaya',
        'biaya_listrik',
        'biaya_transportasi',
        'biaya_lain',
        'cicilan_rumah',
        'kredit_lain',
        'kondisi_lingkungan',
        'skor_character',
        'skor_capacity',
        'skor_collateral',
        'skor_condition',
        'skor_capital',
        'skor_purpose',
        'biaya_hidup',
        'bi_checking_file1',
        'bi_checking_file2',
        'bi_checking_score',
        'bi_checking_balance',
        'bi_checking_past_due'
    ];
}
